name: Deploy

on:
  workflow_run:
    workflows: ["First-CI"]
    types:
      - completed

jobs:
  deploy:

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:

      - name: Deploy on Oracle VM
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/mini-devops
            
            git pull
            
            cat > .env << EOF
            APP_NAME=${{ secrets.APP_NAME }}
            SPRING_PROFILES_ACTIVE=${{ secrets.SPRING_PROFILE }}
          
            POSTGRES_DB=${{ secrets.POSTGRES_DB }}
            POSTGRES_USER=${{ secrets.POSTGRES_USER }}
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PORT=${{ secrets.DB_PORT }}
            EOF
            
            docker compose pull

            docker compose up -d

            docker image prune -f